```python
def primegen():
    # Program code for generating prime numbers

def load_with_fractions():
    # Function to load program with fractions

def execute_program():
    # Function to execute the program

def capture_generated_primes():
    # Function to capture the prime numbers generated

def perform_calculations():
    # Function to perform necessary calculations

def main():
    primegen()  # Run the primegen program
    print("First 15 steps:")
    # Print the first 15 steps
    print("First 20 prime numbers:")
    # Find and print the first 20 prime numbers generated by the program

main()  # Run the main function
```